// This file was autogenerated by ./node_modules/closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../../app/src/angular/controller/dialog.controller.js', ['app.angular.DialogController'], []);
goog.addDependency('../../../../app/src/angular/engine.js', ['app.angular.Engine'], []);
goog.addDependency('../../../../app/src/angular/view/button.view.js', ['app.angular.ButtonView'], ['app.angular.View']);
goog.addDependency('../../../../app/src/angular/view/composed.view.js', ['app.angular.ComposedView'], ['app.angular.View', 'app.iterator.ArrayIterator']);
goog.addDependency('../../../../app/src/angular/view/dialog.view.js', ['app.angular.DialogView'], ['app.angular.ComposedView']);
goog.addDependency('../../../../app/src/angular/view/view.js', ['app.angular.View'], []);
goog.addDependency('../../../../app/src/application/application.js', ['app.Application'], ['app.angular.ButtonView', 'app.angular.DialogController', 'app.angular.DialogView', 'app.angular.Engine', 'app.command.LoginCommand', 'app.dao.TempDataAccess']);
goog.addDependency('../../../../app/src/command/command.js', ['app.command.Interface'], []);
goog.addDependency('../../../../app/src/command/login.command.js', ['app.command.LoginCommand'], ['app.command.Interface']);
goog.addDependency('../../../../app/src/command/logout.command.js', ['app.command.LogoutCommand'], ['app.command.Interface']);
goog.addDependency('../../../../app/src/command/register.command.js', ['app.command.RegisterCommand'], ['app.command.Interface']);
goog.addDependency('../../../../app/src/dao/dao.js', ['app.dao.Interface'], []);
goog.addDependency('../../../../app/src/dao/temp.dao.js', ['app.dao.TempDataAccess'], ['app.dao.Interface']);
goog.addDependency('../../../../app/src/iterator/array.iterator.js', ['app.iterator.ArrayIterator'], ['app.iterator.Iterator']);
goog.addDependency('../../../../app/src/iterator/iterator.js', ['app.iterator.Iterator'], []);
goog.addDependency('../../../../app/src/model/attribute.js', ['app.model.Attribute'], []);
goog.addDependency('../../../../app/src/model/model.js', ['app.model.Model'], ['app.model.Attribute', 'app.validator.ValidatorFactory']);
goog.addDependency('../../../../app/src/model/user.model.js', ['app.model.User'], ['app.model.Attribute', 'app.model.Model', 'app.validator.ValidatorFactory']);
goog.addDependency('../../../../app/src/validator/required.validator.js', ['app.validator.RequiredValidator'], ['app.validator.Interface']);
goog.addDependency('../../../../app/src/validator/validator.factory.js', ['app.validator.ValidatorFactory'], ['app.validator.RequiredValidator']);
goog.addDependency('../../../../app/src/validator/validator.js', ['app.validator.Interface'], []);
goog.addDependency('../../../../app/test/dao.js', ['app.test.suite.DataAccess'], ['app.dao.TempDataAccess']);
goog.addDependency('../../../../app/test/model.js', ['app.test.suite.Model'], ['app.model.Attribute']);
goog.addDependency('../../../../app/test/runner.js', ['app.test.Runner'], ['app.test.suite.DataAccess', 'app.test.suite.Validator']);
goog.addDependency('../../../../app/test/validator.js', ['app.test.suite.Validator'], ['app.model.Attribute', 'app.validator.ValidatorFactory']);
